version: '3'
services:
  maven:
    build: .
    container_name: my-maven-app
    ports:
      - "8080:8080"
    networks:
      - my-network

  # MySql container
  mysql:
    image: mysql:8.1.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fx_deals
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network: